apiVersion: v1
kind: Secret
metadata:
  name: {{ include "turbotic-playground.fullname" . }}-secrets
  labels:
    {{- include "turbotic-playground.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.app.secrets.mongoUri }}
  mongo-uri: {{ .Values.app.secrets.mongoUri }}
  {{- end }}
  {{- if .Values.app.secrets.jwtSecret }}
  jwt-secret: {{ .Values.app.secrets.jwtSecret }}
  {{- end }}
  {{- if .Values.app.secrets.encryptionKey }}
  encryption-key: {{ .Values.app.secrets.encryptionKey }}
  {{- end }}
  {{- if .Values.app.secrets.rabbitMqEndpoint }}
  rabbitmq-endpoint: {{ .Values.app.secrets.rabbitMqEndpoint }}
  {{- end }}
  {{- if .Values.app.secrets.perplexityApiKey }}
  perplexity-api-key: {{ .Values.app.secrets.perplexityApiKey }}
  {{- end }}
  {{- if .Values.app.secrets.azureOpenaiApiKey }}
  azure-openai-api-key: {{ .Values.app.secrets.azureOpenaiApiKey }}
  {{- end }}
  {{- if .Values.app.secrets.azureOpenaiInstanceName }}
  azure-openai-instance-name: {{ .Values.app.secrets.azureOpenaiInstanceName }}
  {{- end }}
  {{- if .Values.app.secrets.azureOpenaiDeploymentName }}
  azure-openai-deployment-name: {{ .Values.app.secrets.azureOpenaiDeploymentName }}
  {{- end }}
  {{- if .Values.app.secrets.azureOpenaiApiVersion }}
  azure-openai-api-version: {{ .Values.app.secrets.azureOpenaiApiVersion }}
  {{- end }}
  {{- if .Values.app.secrets.sendgridApiKey }}
  sendgrid-api-key: {{ .Values.app.secrets.sendgridApiKey }}
  {{- end }}
  {{- if .Values.app.secrets.microsoftClientId }}
  microsoft-client-id: {{ .Values.app.secrets.microsoftClientId }}
  {{- end }}
  {{- if .Values.app.secrets.microsoftClientSecret }}
  microsoft-client-secret: {{ .Values.app.secrets.microsoftClientSecret }}
  {{- end }}
  {{- if .Values.app.secrets.stripeSecretKey }}
  stripe-secret-key: {{ .Values.app.secrets.stripeSecretKey }}
  {{- end }}
  {{- if .Values.app.secrets.stripePublishableKey }}
  stripe-publishable-key: {{ .Values.app.secrets.stripePublishableKey }}
  {{- end }}
  {{- if .Values.realtimeServer.secrets.mongoUri }}
  mongo-uri: {{ .Values.realtimeServer.secrets.mongoUri }}
  {{- end }}
  {{- if .Values.workerNode.secrets.mongoUri }}
  mongo-uri: {{ .Values.workerNode.secrets.mongoUri }}
  {{- end }}
  {{- if .Values.workerNode.secrets.rabbitMqEndpoint }}
  rabbitmq-endpoint: {{ .Values.workerNode.secrets.rabbitMqEndpoint }}
  {{- end }}

